### ISSUE TITLE
Quick launch: unhandled exception when SSH profile is selected

### ISSUE THREAD

**Issue by mjs** [jumptrading/FluentTerminal#173]
FT crashes when a SSH profile is selected in the Quick launch completion list.

The exception is:

```
System.ArgumentException: The value has to be of type ShellProfile.
   at FluentTerminal.App.ViewModels.Profiles.ProfileProviderViewModelBase.set_Model(ShellProfile value)
   at FluentTerminal.App.ViewModels.CommandProfileProviderViewModel.SetProfile(ShellProfile profile)
   at FluentTerminal.App.Dialogs.CustomCommandDialog.CommandTextBox_OnQuerySubmitted(AutoSuggestBox sender, AutoSuggestBoxQuerySubmittedEventArgs args)
```

**Comment by peske** [comment]
Thanks for noticing that @mjs! I've added the fix to https://github.com/felixse/FluentTerminal/pull/481

**Comment by peske** [comment]
Fixed.
