### ISSUE TITLE
cmd.exe shell process randomly errors out after connecting/disconnecting external display

### ISSUE THREAD

**Issue by MaxRis** [jumptrading/FluentTerminal#211]
Was able to see the issue 1 time from 3 attempts on disconnection of external monitor (doesn't happen on connection of external monitor set as primary)

**Comment by MaxRis** [comment]
Can't repro anymore ( Windows 10 1903 Build 18362 )

**Comment by MaxRis** [comment]
posting here repro steps found by @mjs 

```
I did try out the latest release though (0.6.1.0) and did a lot of unplugging and plugging in of external monitors while a cmd.exe tab was running dir /s. After some time, the systray process starting consume a lot of CPU and memory (over 1GB).
The tab eventually became unresponsive and took a long time to eventually close.
An idle powershell also because very sluggish
I was able to start a new powershell tab which worked fine.
```

**Comment by peske** [comment]
Another bug I cannot reproduce. I have two displays, one being primary. I've tried all possible combinations:

- Plugging/unplugging primary;
- Plugging/unplugging secondary;
- Changing screen resolutions on primary/secondary so that they are different, and plugging/unplugging again.

Note: I'm running Win 1909

Few thoughts about this bug:

- FT relies on UWP/Windows infrastructure to handle displays, meaning that it doesn't contain any code which handles displays. For this reason, I believe that the bug isn't in our realm, but in UWP. If so we actually cannot fix it, but hope that Microsoft will fix it in some future version (if it isn't already solved - I cannot reproduce it in 1909).
- This is another of bugs that may vanish when we migrate to `AppWindow` API.

For these reasons, I suggest putting this one on hold for now. Guys?

**Comment by mjs** [comment]
@peske One difference is that I'm still running 1809. 

Were you making these display changes while there was output being generated in FT terminals?

**Comment by mjs** [comment]
I tried replicating this issue again, but with debug logging turned on. It took a lot of plugging and unplugging but the systray eventually crashed (process was gone). The log output was this:

```
2019-11-14 21:33:13.543 +13:00 [ERR] ResizeTerminal: resizing of terminal with id '0' failed with exception: System.Exception: lost connection to agent
   at FluentTerminal.SystemTray.Services.WinPty.WinPtySession.Resize(TerminalSize size)
   at FluentTerminal.SystemTray.Services.TerminalsManager.ResizeTerminal(Byte id, TerminalSize size)
2019-11-14 21:34:51.276 +13:00 [ERR] Unhandled Exception
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at FluentTerminal.SystemTray.Services.TerminalsManager.Write(Byte id, Byte[] data)
   at FluentTerminal.SystemTray.Services.AppCommunicationService.<OnRequestReceived>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2019-11-14 21:34:53.484 +13:00 [ERR] Unhandled Exception
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.CheckWriteOperations()
   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at FluentTerminal.SystemTray.Services.TerminalsManager.Write(Byte id, Byte[] data)
   at FluentTerminal.SystemTray.Services.AppCommunicationService.<OnRequestReceived>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2019-11-14 21:34:53.484 +13:00 [ERR] Unhandled Exception
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.CheckWriteOperations()
   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at FluentTerminal.SystemTray.Services.TerminalsManager.Write(Byte id, Byte[] data)
   at FluentTerminal.SystemTray.Services.AppCommunicationService.<OnRequestReceived>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2019-11-14 21:34:53.484 +13:00 [ERR] Unhandled Exception
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.CheckWriteOperations()
   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at FluentTerminal.SystemTray.Services.TerminalsManager.Write(Byte id, Byte[] data)
   at FluentTerminal.SystemTray.Services.AppCommunicationService.<OnRequestReceived>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
PS C:\Users\Menno\AppData\Local\Packages\53621FSApps.FluentTerminal_87x1pks76srcp\LocalCache\Logs>
```

**Comment by MaxRis** [comment]
@mjs are you running latest upstream?
There (`at FluentTerminal.SystemTray.Services.TerminalsManager.Write(Byte id, Byte[] data)`) already should be try/catch block to prevent unhandled exception propagation https://github.com/jumptrading/FluentTerminal/issues/224
Assumption is that WinPty based process was terminated, but SystemTray receives user input write data faster than UWP part receivss notification about finished WInPty session.

**Comment by mjs** [comment]
@MaxRis I'm running 0.6.1.0. If it's fixed since then - great!

**Comment by mjs** [comment]
I've done some comprehensive testing with the new version and I can no longer reproduce this.
