### ISSUE TITLE
SystemTray process unhandled exception

### ISSUE THREAD

**Issue by MaxRis** [jumptrading/FluentTerminal#214]
Exception happened with laptop carried on the go with possibly weak internet connection.

From SystemTray process log:

```
2019-09-02 18:24:54.035 +01:00 [ERR] Unhandled Exception

System.Exception: lost connection to agent

   at FluentTerminal.SystemTray.Services.WinPty.WinPtySession.Resize(TerminalSize size)

   at FluentTerminal.SystemTray.Services.TerminalsManager.ResizeTerminal(Byte id, TerminalSize size)

   at FluentTerminal.SystemTray.Services.AppCommunicationService.<OnRequestReceived>d__11.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

2019-09-02 18:24:55.708 +01:00 [ERR] Unhandled Exception

System.IO.IOException: Pipe is broken.

   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)

   at System.IO.Pipes.PipeStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)

   at FluentTerminal.SystemTray.Services.TerminalsManager.Write(Byte id, Byte[] data)

   at FluentTerminal.SystemTray.Services.AppCommunicationService.<OnRequestReceived>d__11.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

2019-09-02 18:24:55.709 +01:00 [ERR] Unhandled Exception

System.IO.IOException: Pipe is broken.

   at System.IO.Pipes.PipeStream.CheckWriteOperations()

   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)

   at FluentTerminal.SystemTray.Services.TerminalsManager.Write(Byte id, Byte[] data)

   at FluentTerminal.SystemTray.Services.AppCommunicationService.<OnRequestReceived>d__11.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

Launched profile:
```
2019-09-02 14:33:25.649 +01:00 [DBG] Sending CreateTerminalRequest: [{"Identifier":1,"Id":8,"Size":{"Columns":174,"Rows":41,"$type":"TerminalSize"},"Profile":{"Id":"6ce5703a-3a41-4015-ab90-13a992758846","PreInstalled":false,"Name":"Ferrari Py36 Dev","Arguments":"run -it -w /vcs/ferrari -e PYTHONPATH=/vcs/ferrari -e WORKSPACE=/vcs/ferrari -v C:/Users/%USERNAME%/vcs:/vcs ferrari:dev-py36 bash","Location":"C:\\Program Files\\Docker\\Docker\\Resources\\bin\\docker.exe","WorkingDirectory":"","TabThemeId":2,"LineEndingTranslation":"DoNotModify","EnvironmentVariables":{},"UseConPty":false,"Tag":{"$type":"DelayedHistorySaver"},"TerminalThemeId":"00000000-0000-0000-0000-000000000000","KeyBindings":[],"$type":"ShellProfile"},"SessionType":"WinPty","$type":"CreateTerminalRequest"}]
```

**Comment by MaxRis** [comment]
It looks like we should handle WinPTY's custom exceptions in our own source code https://github.com/microsoft/node-pty/blob/master/deps/winpty/src/libwinpty/winpty.cc#L276
