### ISSUE TITLE
SystemTray's unhandled exception System.IO.IOException: Pipe is broken.

### ISSUE THREAD

**Issue by MaxRis** [jumptrading/FluentTerminal#224]
```
I also appear to have locked fluent up by accidentally starting the wrong type of profile and clicking the (x) before it was fully up.

existing shells have flashing cursors, but can't be interacted with. Quick launch does the above, although not sure how related that is, trying to launch a new ssh profile tab gives:
```

SystemTray logs:

```
2019-10-18 08:39:43.239 +01:00 [ERR] ResizeTerminal: resizing of terminal with id '2' failed with exception: System.Exception: lost connection to agent
   at FluentTerminal.SystemTray.Services.WinPty.WinPtySession.Resize(TerminalSize size)
   at FluentTerminal.SystemTray.Services.TerminalsManager.ResizeTerminal(Byte id, TerminalSize size)
2019-10-18 08:57:33.182 +01:00 [ERR] Unhandled Exception
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at FluentTerminal.SystemTray.Services.TerminalsManager.Write(Byte id, Byte[] data)
   at FluentTerminal.SystemTray.Services.AppCommunicationService.<OnRequestReceived>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2019-10-18 08:57:33.218 +01:00 [ERR] Unhandled Exception
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.CheckWriteOperations()
   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at FluentTerminal.SystemTray.Services.TerminalsManager.Write(Byte id, Byte[] data)
   at FluentTerminal.SystemTray.Services.AppCommunicationService.<OnRequestReceived>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2019-10-18 08:57:33.249 +01:00 [ERR] Unhandled Exception
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.CheckWriteOperations()
   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at FluentTerminal.SystemTray.Services.TerminalsManager.Write(Byte id, Byte[] data)
   at FluentTerminal.SystemTray.Services.AppCommunicationService.<OnRequestReceived>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2019-10-18 08:57:34.811 +01:00 [ERR] Unhandled Exception
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.CheckWriteOperations()
   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at FluentTerminal.SystemTray.Services.TerminalsManager.Write(Byte id, Byte[] data)
   at FluentTerminal.SystemTray.Services.AppCommunicationService.<OnRequestReceived>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by MaxRis** [comment]
Another crash of tray process on docking have happened with following logs:

```
2019-10-24 08:51:58.652 +01:00 [ERR] ResizeTerminal: resizing of terminal with id '3' failed with exception: System.Exception: lost connection to agent
   at FluentTerminal.SystemTray.Services.WinPty.WinPtySession.Resize(TerminalSize size)
   at FluentTerminal.SystemTray.Services.TerminalsManager.ResizeTerminal(Byte id, TerminalSize size)
2019-10-24 08:56:11.782 +01:00 [ERR] Unhandled Exception
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at FluentTerminal.SystemTray.Services.TerminalsManager.Write(Byte id, Byte[] data)
   at FluentTerminal.SystemTray.Services.AppCommunicationService.<OnRequestReceived>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by MaxRis** [comment]
merged into upstream
