### ISSUE TITLE
Crash after system resume from sleep

### ISSUE THREAD

**Issue by mjs** [jumptrading/FluentTerminal#253]
Experienced by @cjw296 . See attached logs.
[fluentterminal.app20191211.log](https://github.com/jumptrading/FluentTerminal/files/3954871/fluentterminal.app20191211.log)
[fluentterminal.systemtray20191211.log](https://github.com/jumptrading/FluentTerminal/files/3954872/fluentterminal.systemtray20191211.log)

**Comment by MaxRis** [comment]
@mjs @cjw296 

Unfortunately, I can't find anything interesting in the logs related to the experienced crash.
According to the UWP app logs, it seems only UWP process was crashed because of app startup record in the log:
```
2019-12-11 18:24:05.169 +00:00 [FTL] Initialized
```
Tray process seems was not damaged by this crash.

**Comment by mjs** [comment]
@MaxRis I'm confused. What about this in the system tray from the system tray logs attached to this issue? Seems pretty relevant.

```
2019-12-11 08:11:34.090 +00:00 [ERR] Unobserved Task Exception
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.ArgumentException: Either the IAsyncResult object did not come from the corresponding async method on this type, or EndRead was called multiple times with the same IAsyncResult.
   at System.IO.Stream.EndRead(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at FluentTerminal.SystemTray.Services.WinPty.WinPtySession.<<ListenToStdOut>b__30_0>d.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentException: Either the IAsyncResult object did not come from the corresponding async method on this type, or EndRead was called multiple times with the same IAsyncResult.
   at System.IO.Stream.EndRead(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at FluentTerminal.SystemTray.Services.WinPty.WinPtySession.<<ListenToStdOut>b__30_0>d.MoveNext()<---

2019-12-11 10:49:30.952 +00:00 [DBG] DisplayTerminalOutput failed. Exception: ["System.ArgumentException: Empty path name is not legal.\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at FluentTerminal.SystemTray.Services.TerminalsManager.DisplayTerminalOutput(Byte terminalId, Byte[] output)"]

```

**Comment by MaxRis** [comment]
@mjs these 2 records are not "unhandled" and were not resulted to the crash. The timing when these exceptions are logged and the time of the new UWP process startup (seems after crash) also is very different.

`[ERR] Unobserved Task Exception` such kind of exceptions started to be logged after recent @peske changes (I guess, suggested by ReSharper). 

`[DBG] DisplayTerminalOutput failed.` seems is handled properly and was not resulted into the crash as well.

**Comment by mjs** [comment]
@MaxRis ok, thanks for clarifying

**Comment by MaxRis** [comment]
Agreed to review source code to place more logging in case of unhandled exceptions.

**Comment by MaxRis** [comment]
@mjs @peske I was not able to find the right place where to put additional exceptions handling.

@peske might you will able to take a look if we can somehow improve logging of exceptions and give your opinion on that?

Both UWP and TrayProcess apps define `UnhandledException` handlers which should catch all unhandled `managed` exceptions.
I've tried to generate native `AccessViolationException` by calling DllImported WinAPI method and UWP process was just crashing without `UnhandledException` handler invocation (no log records available). Possibly, native code exception is the cause of crash in the original report for this Issue. I can imagine similar exception which comes from WebView's internals through XAML based managed code, for example (this sounds like the worst scenario which we can't handle). Interesting that usage of `[HandleProcessCorruptedStateExceptions]` method attribute inside UWP app doesn't help to `catch` occurred `AccessViolationException` exception.

**Comment by mjs** [comment]
This has been pushed as far as is reasonable and may not be happening for users any more. Closing.
