### ISSUE TITLE
Dropping of tab to create new window causes crash of UWP process

### ISSUE THREAD

**Issue by MaxRis** [jumptrading/FluentTerminal#254]
Tab's drag`n`drop to new window is broken on latest master.
It just crashes with unhandled exception.

```
2019-12-12 15:18:19.517 +04:00 [ERR] Unhandled Exception
System.Exception: A COM call to an ASTA was blocked because the call chain originated in or passed through another ASTA. This call pattern is deadlock-prone and disallowed by apartment call control.A COM call (IID: {C50898F6-C536-5F47-8583-8B2C2438A13B}, method index: 3) to an ASTA (thread 18016) was blocked because the call chain originated in or passed through another ASTA (thread 17936). This call pattern is deadlock-prone and disallowed by apartment call control.
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at FluentTerminal.RuntimeComponent.WebAllowedObjects.TerminalBridge.<>c__DisplayClass2_0.<_terminalEventListener_OnOutput>b__0()
   at FluentTerminal.RuntimeComponent.WebAllowedObjects.EventDispatcher.<>c__DisplayClass0_0.<Dispatch>b__0()
```

This crash doesn't happen on latest shared build 0.6.1.4

cc: @peske

**Comment by peske** [comment]
Marking this one as duplicate since I've opened the same issue, with bit better description: https://github.com/jumptrading/FluentTerminal/issues/255. Closing.
