### ISSUE TITLE
Right mouse click to copy selected text crashes Fluent UWP app

### ISSUE THREAD

**Issue by MaxRis** [jumptrading/FluentTerminal#264]
From logs:

```
2020-01-19 23:17:37.425 +02:00 [ERR] Unhandled Exception
System.Runtime.InteropServices.COMException (0x8000001D): Activating a single-threaded class from MTA is not supported (Exception from HRESULT: 0x8000001D)
   at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
   at Windows.ApplicationModel.DataTransfer.Clipboard.SetContent(DataPackage content)
   at FluentTerminal.App.Services.ClipboardService.SetText(String text)
   at FluentTerminal.App.ViewModels.TerminalViewModel.CopyText(String text)
   at FluentTerminal.App.ViewModels.TerminalViewModel.Terminal_KeyboardCommandReceived(Object sender, String e)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
```

![2020-01-19_23-24-02-crash-on-copy](https://user-images.githubusercontent.com/1928902/72688741-dd82ac00-3b12-11ea-84a7-5e816207cf31.gif)

cc: @peske

**Comment by peske** [comment]
Fixed in https://github.com/felixse/FluentTerminal/pull/656
